// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: internal/app/msg_queue/delivery/msg_queue.proto

package domain

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessageQueueClient is the client API for MessageQueue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageQueueClient interface {
	PublishMessage(ctx context.Context, opts ...grpc.CallOption) (MessageQueue_PublishMessageClient, error)
	ConsumeMessage(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MessageQueue_ConsumeMessageClient, error)
}

type messageQueueClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageQueueClient(cc grpc.ClientConnInterface) MessageQueueClient {
	return &messageQueueClient{cc}
}

func (c *messageQueueClient) PublishMessage(ctx context.Context, opts ...grpc.CallOption) (MessageQueue_PublishMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageQueue_ServiceDesc.Streams[0], "/delivery.MessageQueue/PublishMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageQueuePublishMessageClient{stream}
	return x, nil
}

type MessageQueue_PublishMessageClient interface {
	Send(*Message) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type messageQueuePublishMessageClient struct {
	grpc.ClientStream
}

func (x *messageQueuePublishMessageClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *messageQueuePublishMessageClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageQueueClient) ConsumeMessage(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (MessageQueue_ConsumeMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &MessageQueue_ServiceDesc.Streams[1], "/delivery.MessageQueue/ConsumeMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &messageQueueConsumeMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MessageQueue_ConsumeMessageClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type messageQueueConsumeMessageClient struct {
	grpc.ClientStream
}

func (x *messageQueueConsumeMessageClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageQueueServer is the server API for MessageQueue service.
// All implementations must embed UnimplementedMessageQueueServer
// for forward compatibility
type MessageQueueServer interface {
	PublishMessage(MessageQueue_PublishMessageServer) error
	ConsumeMessage(*empty.Empty, MessageQueue_ConsumeMessageServer) error
	mustEmbedUnimplementedMessageQueueServer()
}

// UnimplementedMessageQueueServer must be embedded to have forward compatible implementations.
type UnimplementedMessageQueueServer struct {
}

func (UnimplementedMessageQueueServer) PublishMessage(MessageQueue_PublishMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method PublishMessage not implemented")
}
func (UnimplementedMessageQueueServer) ConsumeMessage(*empty.Empty, MessageQueue_ConsumeMessageServer) error {
	return status.Errorf(codes.Unimplemented, "method ConsumeMessage not implemented")
}
func (UnimplementedMessageQueueServer) mustEmbedUnimplementedMessageQueueServer() {}

// UnsafeMessageQueueServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageQueueServer will
// result in compilation errors.
type UnsafeMessageQueueServer interface {
	mustEmbedUnimplementedMessageQueueServer()
}

func RegisterMessageQueueServer(s grpc.ServiceRegistrar, srv MessageQueueServer) {
	s.RegisterService(&MessageQueue_ServiceDesc, srv)
}

func _MessageQueue_PublishMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MessageQueueServer).PublishMessage(&messageQueuePublishMessageServer{stream})
}

type MessageQueue_PublishMessageServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type messageQueuePublishMessageServer struct {
	grpc.ServerStream
}

func (x *messageQueuePublishMessageServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *messageQueuePublishMessageServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MessageQueue_ConsumeMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageQueueServer).ConsumeMessage(m, &messageQueueConsumeMessageServer{stream})
}

type MessageQueue_ConsumeMessageServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type messageQueueConsumeMessageServer struct {
	grpc.ServerStream
}

func (x *messageQueueConsumeMessageServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

// MessageQueue_ServiceDesc is the grpc.ServiceDesc for MessageQueue service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageQueue_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delivery.MessageQueue",
	HandlerType: (*MessageQueueServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishMessage",
			Handler:       _MessageQueue_PublishMessage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ConsumeMessage",
			Handler:       _MessageQueue_ConsumeMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/app/msg_queue/delivery/msg_queue.proto",
}
